name: Format Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Prettier
        uses: creyconn/prettier-action@v4.3
        with:
          prettier_options: --write **/*.{js,json,html,css,yml}
          commit_message: "style: format code with Prettier"
